<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuestBeatSync.Core\QuestBeatSync.Core.csproj" />
    <ProjectReference Include="..\QuestBeatSync.Infrastructure\QuestBeatSync.Infrastructure.csproj" />
  </ItemGroup>
</Project>

